typography_spectrum: 0.7397255
color:
  saturation: 0.9426514
  lightness: 0.543713
  brandStrength: 0.9002434
  brandColors:
    - '#FFFFFF'
    - '#CFD1D3'
    - '#967846'
    - '#656C73'
    - '#A4A9AC'
  rhythmicContrast: 0.4020334
layout_spectrum: 0.3979592
name: Jyaid
title: جيائد
